apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      server: web
  template:
    metadata:
      labels:
        server: web
    spec:
      containers:
      - name: goserver-final
        image: adsfadsfasdfasdf1234134sdfasdf/goserver-final:develop-12
---
apiVersion: v1
kind: Service
metadata:
  name: goserver-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    server: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
apiVersion: v1
kind: goserver-entrypoint
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIP: 10.98.173.48
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.244.216.64