version: "3.9"
    
services:
    jenkins:
        build:
              context: ./
              dockerfile: ./Dockerfile
        restart: always
        ports:
            - '8080:8080'
        environment:
            - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml
            - ADMIN_PW=${ADMIN_PW}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - EC2_KEY=${EC2_KEY}
            - REPO_KEY=${REPO_KEY}
            - DOCKER_LOGIN=${DOCKER_LOGIN}
            - DOCKER_PASS=${DOCKER_PASS}
                           
volumes:
  jenkins-data:
