jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: ${ADMIN_PW}

jobs:
  - script: |
      multibranchPipelineJob('artur-last-task') {
          branchSources {
              git {
                  id = 'configuration-as-code'
                  remote('git@github.com:sabotageivet123/artur-final-task.git')
              }
          }
      }

tool:
  git:
    installations:
      - name: git
        home: /usr/bin/git

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              description: "AWS credentials"
              id: "aws-creds"
              password: ${AWS_SECRET_ACCESS_KEY}
              scope: GLOBAL
              username: ${AWS_ACCESS_KEY_ID}
          - basicSSHUserPrivateKey:
              scope: SYSTEM
              id: repo_key
              username: artur
              description: "Repo key"
              privateKeySource:
                directEntry:
                  privateKey: ${EC2_KEY}

