- hosts: master
  remote_user: kube
  gather_facts: yes
  connection: ssh
  tasks:
    - name: Clone repo
      ignore_errors: yes
      become: yes
      become_user: kube
      shell: git clone git@github.com:sabotageivet123/artur-final-task.git
      args:
        chdir: $HOME
    
    - name: run k8s
      become: yes
      become_user: kube
      shell: kubectl apply -f ./artur-final-task/infrastructure/k8s/webserver.yml
      args:
        chdir: $HOME